image: node:13

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

build_snapshot:
  stage: build
  before_script:
    - npm install
    - echo "export const VERSION = '`git describe --tags`'" > src/environments/version.ts
  script: npm run build
  artifacts:
    when: always
    paths:
      - dist/main/*
    expire_in: 1 week
  except:
    - tags

publish_release:
  stage: release
  before_script:
    - npm install
    - echo "export const VERSION = '`git describe --tags`'" > src/environments/version.ts
  script: npm run buildprod
  artifacts:
    when: always
    paths:
      - dist/main/*
    expire_in: 1 week
  only:
    - tags

semver:
  stage: release
  before_script:
    - npm install @semantic-release/gitlab
    - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script: npx semantic-release -t \${version}
  only:
    - master
