image: node:13

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

build_snapshot:
  stage: build
  before_script:
    - npm install
    - npm install --save @angular/material @angular/cdk
  script: npm run build
  artifacts:
    when: always
    paths:
      - dist/main/*
    expire_in: 1 week

publish_release:
  stage: release
  before_script:
    - npm install
    - npm install --save @angular/material @angular/cdk
  script: npm run buildprod
  artifacts:
    when: always
    paths:
      - dist/main/*
    expire_in: 1 week
  only:
    - tags

semver:
  stage: release
  before_script:
    - npm install @semantic-release/gitlab
    - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script: npx semantic-release -t \${version}
  only:
    - master
